---
abstract: 'Override REST methods to Plack apps via POST'
author:
  - 'David E. Wheeler <david@kineticode.com>'
build_requires:
  Module::Build: 0.30
  Test::More: 0.70
configure_requires:
  Module::Build: 0.30
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-MethodOverride
provides:
  Plack::Middleware::MethodOverride:
    file: lib/Plack/Middleware/MethodOverride.pm
    version: 0.10
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  Plack: 0.9929
  Test::Builder: 0.70
  URI: 0
  perl: 5.008001
resources:
  bugtracker: http://github.com/theory/plack-middleware-methodoverride/issues/
  homepage: http://search.cpan.org/dist/Plack-Middleware-MethodOverride/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/plack-middleware-methodoverride/tree/
version: 0.10
